# Generated by Django 2.0.4 on 2018-08-22 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dollarial.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dollarial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', dollarial.fields.PriceField(verbose_name='Amount')),
                ('currency', dollarial.fields.CurrencyField(choices=[('D', '$'), ('R', '﷼'), ('E', '€')], max_length=1, verbose_name='Currency')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('wage', dollarial.fields.PriceField(default=0, verbose_name='Wage')),
                ('status', models.CharField(choices=[('I', 'In Review'), ('R', 'Rejected'), ('A', 'Accepted')], default='I', max_length=1, verbose_name='Status')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='BankPayment',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.Transaction')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('finance.transaction',),
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.Transaction')),
                ('final_amount', dollarial.fields.PriceField(verbose_name='Final Amount')),
                ('final_currency', dollarial.fields.CurrencyField(choices=[('D', '$'), ('R', '﷼'), ('E', '€')], max_length=1, verbose_name='Final Currency')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('finance.transaction',),
        ),
        migrations.CreateModel(
            name='ExternalPayment',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.Transaction')),
                ('destination_number', models.CharField(max_length=63, verbose_name='Destination Account Number')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('finance.transaction',),
        ),
        migrations.CreateModel(
            name='FormPayment',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.Transaction')),
                ('first_name', models.CharField(blank=True, max_length=63, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=63, verbose_name='Last Name')),
                ('phone_number', models.CharField(blank=True, max_length=32, verbose_name='Phone Number')),
                ('security_number', models.CharField(blank=True, max_length=10, verbose_name='Security Number')),
                ('passport_number', models.CharField(blank=True, max_length=10, verbose_name='Passport Number')),
                ('exam_username', models.CharField(blank=True, max_length=63, verbose_name='Exam Username')),
                ('exam_password', models.CharField(blank=True, max_length=63, verbose_name='Exam Password')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='Exam Date')),
                ('exam_country', models.CharField(blank=True, max_length=63, verbose_name='Exam Country')),
                ('exam_city', models.CharField(blank=True, max_length=63, verbose_name='Exam City')),
                ('exam_center', models.CharField(blank=True, max_length=256, verbose_name='Exam Center')),
                ('university_link', models.URLField(blank=True, verbose_name='University Link')),
                ('university_username', models.CharField(blank=True, max_length=63, verbose_name='University Username')),
                ('university_password', models.CharField(blank=True, max_length=63, verbose_name='University Password')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dollarial.PaymentType', verbose_name='Payment Type')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('finance.transaction',),
        ),
        migrations.CreateModel(
            name='InternalPayment',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.Transaction')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('finance.transaction',),
        ),
        migrations.CreateModel(
            name='ReverseInternalPayment',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.Transaction')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('finance.transaction',),
        ),
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_finance.transaction_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='internalpayment',
            name='reverse_payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.ReverseInternalPayment', verbose_name='Reverse Payment'),
        ),
    ]
