# Generated by Django 2.0.4 on 2018-08-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('I', 'In Review'), ('R', 'Rejected'), ('A', 'Accepted')], default='I', max_length=1, verbose_name='Status'),
        ),
    ]
