# Generated by Django 2.0.4 on 2018-08-16 13:16

from django.db import migrations, models
import django.db.models.deletion
import dollarial.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dollarial', '0004_auto_20180811_2005'),
        ('finance', '0002_transaction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPayment',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.Transaction')),
                ('first_name', models.CharField(blank=True, max_length=63, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=63, verbose_name='Last Name')),
                ('phone_number', models.CharField(blank=True, max_length=32, verbose_name='Phone Number')),
                ('security_number', models.CharField(blank=True, max_length=10, verbose_name='Security Number')),
                ('passport_number', models.CharField(blank=True, max_length=10, verbose_name='Passport Number')),
                ('exam_username', models.CharField(blank=True, max_length=63, verbose_name='Exam Username')),
                ('exam_password', models.CharField(blank=True, max_length=63, verbose_name='Exam Password')),
                ('exam_date', models.DateField(blank=True, verbose_name='Exam Date')),
                ('exam_country', models.CharField(blank=True, max_length=63, verbose_name='Exam Country')),
                ('exam_city', models.CharField(blank=True, max_length=63, verbose_name='Exam City')),
                ('exam_center', models.CharField(blank=True, max_length=256, verbose_name='Exam Center')),
                ('university_link', models.URLField(blank=True, verbose_name='University Link')),
                ('university_username', models.CharField(blank=True, max_length=63, verbose_name='University Username')),
                ('university_password', models.CharField(blank=True, max_length=63, verbose_name='University Password')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dollarial.PaymentType', verbose_name='Payment Type')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('finance.transaction',),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wage',
            field=dollarial.fields.PriceField(decimal_places=2, default=0, max_digits=12, verbose_name='Wage'),
        ),
    ]
