# Generated by Django 2.0.4 on 2018-08-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20180827_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('I', 'In Review'), ('R', 'Rejected'), ('A', 'Accepted')], db_index=True, default='I', max_length=1, verbose_name='Status'),
        ),
    ]
