# Generated by Django 2.0.4 on 2018-08-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20180816_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpayment',
            name='exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='Exam Date'),
        ),
    ]
