# Generated by Django 2.0.4 on 2018-08-18 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20180818_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPayment',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.Transaction')),
                ('destination_number', models.CharField(max_length=63, verbose_name='Destination Account Number')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('finance.transaction',),
        ),
        migrations.CreateModel(
            name='InternalPayment',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.Transaction')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('finance.transaction',),
        ),
        migrations.CreateModel(
            name='ReverseInternalPayment',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.Transaction')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('finance.transaction',),
        ),
        migrations.AddField(
            model_name='internalpayment',
            name='reverse_payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.ReverseInternalPayment', verbose_name='Reverse Payment'),
        ),
    ]
