# Generated by Django 2.0.4 on 2018-07-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_add_clerk_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='notification_preference',
            field=models.CharField(choices=[('S', 'sms'), ('E', 'email')], default='S', max_length=1),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
