# Generated by Django 2.0.4 on 2018-08-01 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20180731_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.BigIntegerField(default=0, verbose_name='credit')),
                ('currency', models.CharField(choices=[('R', 'Rial'), ('D', 'Dollar'), ('E', 'Euro')], default='R', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='notification_preference',
            field=models.CharField(choices=[('S', 'sms'), ('E', 'email')], default='S', max_length=1, verbose_name='Notification Preference'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'currency')},
        ),
    ]
