# Generated by Django 2.0.4 on 2018-08-04 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_auto_20180804_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerk',
            name='is_employee',
            field=models.BooleanField(default=True, verbose_name='is Employee'),
        ),
        migrations.AlterField(
            model_name='clerk',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
