# Generated by Django 2.0.4 on 2018-08-04 12:16

from django.db import migrations
import dollarial.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_auto_20180804_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='credit',
            field=dollarial.fields.PriceField(decimal_places=2, default=0, max_digits=12, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=dollarial.fields.CurrencyField(choices=[('D', 'Dollar'), ('R', 'Rial'), ('E', 'Euro')], max_length=1),
        ),
    ]
