# Generated by Django 2.0.4 on 2018-08-04 13:07

from django.db import migrations
import dollarial.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_auto_20180804_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='banned',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=dollarial.fields.CurrencyField(choices=[('D', 'Dollar'), ('R', 'Rial'), ('E', 'Euro')], default='R', max_length=1, verbose_name='Currency'),
        ),
    ]
