# Generated by Django 2.0.4 on 2018-08-27 09:08

from django.db import migrations, models
import dollarial.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dollarial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='max_amount',
            field=dollarial.fields.PriceField(default=100000000, null=True, verbose_name='Maximum Amount'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification_preference',
            field=models.CharField(choices=[('S', 'sms'), ('E', 'email'), ('B', 'both')], default='B', max_length=1, verbose_name='Notification Preference'),
        ),
    ]
