# Generated by Django 2.0.4 on 2018-08-11 10:24

import bitfield.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import dollarial.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dollarial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('min_amount', dollarial.fields.PriceField(decimal_places=2, default=1, max_digits=12, verbose_name='Minimum Amount')),
                ('max_amount', dollarial.fields.PriceField(decimal_places=2, default=1000000, max_digits=12, verbose_name='Minimum Amount')),
                ('price', dollarial.fields.PriceField(decimal_places=2, default=0, max_digits=12, verbose_name='Fixed Price')),
                ('wage_percentage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Wage Percentage')),
                ('currency', dollarial.fields.CurrencyField(choices=[('D', 'Dollar'), ('R', 'Rial'), ('E', 'Euro')], default='R', max_length=1, verbose_name='Currency')),
                ('fixed_price', models.BooleanField(default=True, verbose_name='Fixed Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('required_fields', bitfield.models.BitField(('general_info', 'personal_info', 'exam_info', 'university_info'), default=None)),
                ('transaction_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dollarial.PaymentGroup', verbose_name='Group')),
            ],
        ),
    ]
