# Generated by Django 2.0.4 on 2018-08-11 12:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import dollarial.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dollarial', '0002_paymentgroup_paymenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='max_amount',
            field=dollarial.fields.PriceField(blank=True, decimal_places=2, default=1000000, max_digits=12, verbose_name='Minimum Amount'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='min_amount',
            field=dollarial.fields.PriceField(blank=True, decimal_places=2, default=1, max_digits=12, verbose_name='Minimum Amount'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='price',
            field=dollarial.fields.PriceField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Fixed Price'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='transaction_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dollarial.PaymentGroup', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='wage_percentage',
            field=models.PositiveSmallIntegerField(default=9, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Wage Percentage'),
        ),
    ]
