# Generated by Django 2.0.4 on 2018-08-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dollarial', '0002_auto_20180827_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification_preference',
            field=models.CharField(choices=[('S', 'sms'), ('E', 'email'), ('B', 'both'), ('N', 'none')], default='B', max_length=1, verbose_name='Notification Preference'),
        ),
    ]
