# Generated by Django 2.0.4 on 2018-08-11 15:35

from django.db import migrations
import dollarial.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dollarial', '0003_auto_20180811_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='max_amount',
            field=dollarial.fields.PriceField(decimal_places=2, default=1000000, max_digits=12, null=True, verbose_name='Minimum Amount'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='min_amount',
            field=dollarial.fields.PriceField(decimal_places=2, default=1, max_digits=12, null=True, verbose_name='Minimum Amount'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='price',
            field=dollarial.fields.PriceField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Fixed Price'),
        ),
    ]
