# Generated by Django 2.0.4 on 2018-08-19 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0003_auto_20180819_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Transaction', verbose_name='Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_before', models.CharField(choices=[('I', 'In Review'), ('R', 'Rejected'), ('A', 'Accepted')], max_length=1, verbose_name='Status Before')),
                ('action', models.CharField(choices=[('A', 'Accept'), ('R', 'Reject'), ('S', 'Skip')], max_length=1, verbose_name='Action')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Transaction', verbose_name='Transaction')),
            ],
        ),
    ]
