# Generated by Django 2.0.4 on 2018-08-19 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewhistory',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time'),
        ),
    ]
